name: CI

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Unit Tests
        run: ./gradlew clean testDebug
